baseurl = "https://admin.dropbyte.ch/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "red"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "DropByte Admin Panel"
    subtitle = "Quick Links for DropByte's Backend"
    keywords = ""
    copyright = "DropByte 2020"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "DropByte Admin Panel"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "dropbyte"
        name = "DropByte"
        url = "https://dropbyte.ch"
      [[languages.en.menu.main]]
        identifier = "quickbyte"
        name = "QuickByte"
        url = "https://learn.dropbyte.ch"
